# Generated by Django 4.1.3 on 2022-11-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
    ]
