# Generated by Django 4.1.3 on 2022-11-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_author_email_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock_status',
            field=models.CharField(default='LOW', max_length=10),
        ),
    ]
