# Generated by Django 4.1.3 on 2022-11-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_book_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock_status',
            field=models.CharField(default='Out of stock', max_length=10),
        ),
    ]
